# Generated by Django 3.2 on 2021-05-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishapp', '0002_registerdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdb',
            name='Username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
