# Generated by Django 3.2 on 2021-06-04 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fishapp', '0005_cart_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=20, null=True)),
                ('lastname', models.CharField(blank=True, max_length=20, null=True)),
                ('district', models.CharField(blank=True, max_length=20, null=True)),
                ('street_address', models.CharField(blank=True, max_length=30, null=True)),
                ('appartment', models.CharField(blank=True, max_length=20, null=True)),
                ('town', models.CharField(blank=True, max_length=20, null=True)),
                ('pin', models.IntegerField(blank=True, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('cartid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fishapp.cart')),
            ],
        ),
    ]
