# Generated by Django 3.2 on 2021-04-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigfishapp', '0002_rename_addadmin_admindb'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindb',
            name='FileUpload',
            field=models.ImageField(null=True, upload_to='adminimage/'),
        ),
    ]
