# Generated by Django 3.2 on 2021-04-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigfishapp', '0003_admindb_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindb',
            name='Status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
