# Generated by Django 3.2 on 2021-04-29 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bigfishapp', '0005_rename_status_admindb_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admindb',
            name='Action',
        ),
    ]
