# Generated by Django 3.2 on 2021-05-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigfishapp', '0008_productdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='recipedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recipe_Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Recipe_Ingredience', models.CharField(blank=True, max_length=100, null=True)),
                ('Recipe_Instruction', models.CharField(blank=True, max_length=100, null=True)),
                ('Image', models.ImageField(null=True, upload_to='recipeimage/')),
            ],
        ),
    ]
