# Generated by Django 3.2 on 2021-05-04 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bigfishapp', '0009_recipedb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipedb',
            old_name='Recipe_Ingredience',
            new_name='Recipe_Ingredients',
        ),
        migrations.RenameField(
            model_name='recipedb',
            old_name='Recipe_Instruction',
            new_name='Recipe_Instructions',
        ),
    ]
