# Generated by Django 3.2 on 2021-05-04 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bigfishapp', '0010_auto_20210504_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipedb',
            old_name='Image',
            new_name='Recipe_Image',
        ),
    ]
